---
title: "I Swear, You're Not Stupid..."
format:
    html:
        toc: true
        layout: 
            title: false
title-block-banner: true
page-layout: article
---
# About This Blog
You're not stupid, you're just out of practice.

# Data Science Topics
## Regression
There's tons to learn about regression, but I'll just give you a quick overview.

<p><b>Types of Regression</b></p>
<p>There are several types of regression analysis, including:</p>
<ul>
- Linear Regression: Predicts a dependent variable using a linear equation with one or more independent variables. It's the most straightforward type of regression, used when the relationship between variables is linear.
- Logistic Regression: Used for binary outcomes (e.g., success/failure). It estimates probabilities using a logistic function, making it suitable for classification problems.
- Polynomial Regression: Extends linear regression by allowing the model to fit nonlinear relationships through polynomial terms of independent variables.
- Ridge and Lasso Regression: These are extensions of linear regression that include regularization terms to prevent overfitting, with Lasso also allowing for feature selection by shrinking some coefficients to zero.
</ul>
> Note: For more information, check out [this](https://towardsdatascience.com/a-quick-introduction-to-linear-regression-148689d59e60) article.


### Linear Regression

Here's what linear regression looks like:

### Logistic Regression
 logistic regression is a type of regression that is used to predict a binary outcome.


# Design Cheat Sheets
## Web Design
## Data Visualization
## Colour Theory