---
title: "Insight through Data"
date: 5/31/2024
categories: ["insights", "python"]
format:
  html:
    code-fold: false
jupyter: python3
toc: true
---

## Crafting Visual Narratives for Corporate Strategy

:::{.callout-important}
 All data in this case study is anonymized to protect confidentiality. Details have been altered, but the depicted processes and insights are accurately represented.
:::

In my role as the Data Insights Specialist at the Center for Employment Opportunities, I led the development of KPI visuals and directed the overall strategy for each quarterly board report. My responsibilities ranged from deciding which insights to present and shaping the narrative, to designing the visualizations. 

Here, I'll share a glimpse into how I'd transform raw data [from various departments] into engaging visual stories that inform strategic and operational decisions. It’s all about turning complex data into clear, useful insights, even for those who aren’t familiar with data science or statistical jargon. 
<!-- I’ll share the methods we used to communicate effectively, and the real-world challenges and successes me and the team encountered along the way. -->

Each quarter, I set these goals for myself:

<ul>
<li><b>Show Org-Wide Performance:</b> Ensure strategic alignment with fiscal year objectives.</li>
<li><b>Share Our Strategy for Improvement:</b> Highlight key initiatives and outcomes</li>
<li><b>Delivering Actionable Insights:</b> Provide clear, impactful information to the board./li>
</ul>

## Handling the Data


::: {.observable}
<!-- // Observable notebook embed code or link here -->
:::


## Analysis
Include any specific figures or outputs from the notebook:


```{python}
import numpy as np
```



## Telling The Story
Include the Datawrapper iframe here:
<!-- <iframe title="KPI Dashboard" aria-label="Dashboard" src="https://datawrapper.dwcdn.net/chartID/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400"></iframe> -->
