---
title: I Built An Enterprise ChatBot!
# date: 6/17/2024
# toc: false
# fields: [image, date, title, reading-time, description] 
description: "An interactive tool that offers users answers to common questions about training schedules, services, and resources available through NEST."
projectLink: "https://pathwaypal.streamlit.app"
code: "https://github.com/ligea-alexander/pathwaypal_chatbot"
languages:
  - Python
  - Elasticsearch
  - AI
thumbnail: pathwaypal-app.png
---

Lorem ipsum Vivamus tincidunt nisi a suscipit consequat. Praesent eget convallis neque, ac scelerisque eros. Integer aliquet, elit et tempor convallis, sem libero tincidunt dolor, vitae tempor magna quam at nisi. Sed elementum ac tortor at fringilla. Aliquam et urna congue, tincidunt ipsum quis, congue nisl. Phasellus non sem massa.

Donec quis interdum sem. Mauris ut arcu erat. Sed nisl tellus, consectetur ut tincidunt id, porttitor vel sapien. Pellentesque in lorem vitae sem euismod interdum. Phasellus fermentum consectetur velit. Duis purus diam, mattis vitae dui et, egestas tincidunt nisl. Pellentesque placerat fermentum purus eget pulvinar. Ut fringilla placerat leo, id luctus ipsum elementum non. Suspendisse accumsan metus non dolor blandit vehicula. Nulla sit amet sodales ipsum.